name: ChickenGrabber
version: 1.0
main: net.bappity.ChickenGrabber
api-version: '1.20'
commands:
  chickengrabber:
    description: Main command for the Chicken Grabber plugin
    usage: /chickengrabber <sub-command>
    permission: ChickenGrabber.use
    aliases: []